version: 2
updates:
  - package-ecosystem: nuget
    directory: "/BibliotecaCEITI"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      google-apis:
        patterns:
          - "Google.Apis*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
